# Generated by Django 5.2.16 on 2026-08-18 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='business.salon')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=10)),
                ('category', models.CharField(choices=[('service', 'Pagamento de Serviço'), ('commission', 'Pagamento de Comissão'), ('salary', 'Salário Fixo'), ('utility', 'Despesa Fixa (Água, Luz, Aluguel)'), ('supplier', 'Fornecedores (Produtos)'), ('others', 'Outros')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date_occurred', models.DateField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financial.bankaccount')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.appointment')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.employee')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business.salon')),
            ],
            options={
                'db_table': 'financial_transactions',
                'ordering': ['-date_occurred', '-created_at'],
            },
        ),
    ]
