# Generated by Django 5.2.16 on 2026-08-18 12:35

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL amigável para o salão.', unique=True, verbose_name='Slug')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome do Salão')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('email', models.EmailField(help_text='Email para contato e login.', max_length=254, unique=True, verbose_name='Email de Contato')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salon_logo/', verbose_name='Logo do Salão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('operating_hours', models.JSONField(blank=True, default=dict, null=True, verbose_name='Horário de Funcionamento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salon_address', to='core.address', verbose_name='Endereço do Salão')),
                ('owners', models.ManyToManyField(related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salão',
                'verbose_name_plural': 'Salões',
                'db_table': 'salon',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=20)),
                ('role', models.CharField(choices=[('manager', 'Gerente/Administrador'), ('receptionist', 'Recepcionista'), ('professional', 'Profissional da Beleza'), ('support', 'Apoio (Faxina, Manutenção)')], default='professional', max_length=20)),
                ('contract_type', models.CharField(choices=[('fixed', 'Fixo (CLT/Mensalista)'), ('commission', 'Comissionado (Autônomo/Parceiro)')], default='commission', max_length=20)),
                ('is_schedulable', models.BooleanField(default=True, help_text='Aparece na agenda para clientes?')),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: 50.00 para 50%', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.salon')),
            ],
            options={
                'db_table': 'employee',
                'unique_together': {('cpf_cnpj', 'salon')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('cpf', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='business.salon')),
            ],
            options={
                'db_table': 'customers',
                'unique_together': {('phone', 'salon')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'services',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ServiceSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Imagem')),
                ('duration_minutes', models.IntegerField(verbose_name='Duração em minutos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='business.salon')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salons', to='business.service')),
            ],
            options={
                'verbose_name': 'Serviço do Salão',
                'verbose_name_plural': 'Serviços do Salão',
                'db_table': 'services_salon',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionais')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=50, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='business.customer')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_appointments', to='business.employee', verbose_name='Profissional')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='business.salon', verbose_name='Salão')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_appointments', to='business.servicesalon', verbose_name='Serviço Agendado')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'appointments',
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), expressions=[('professional', '='), ('time_range', '&&')], name='prevent_double_booking')],
            },
        ),
    ]
