# Generated by Django 5.2.16 on 2026-08-23 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_appointment_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total dos Serviços'),
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Cobrado')),
                ('duration_minutes', models.IntegerField(verbose_name='Duração (minutos)')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_items', to='business.servicesalon')),
            ],
            options={
                'verbose_name': 'Item do Agendamento',
                'verbose_name_plural': 'Itens do Agendamento',
                'db_table': 'appointment_items',
            },
        ),
    ]
