# Generated by Django 5.2.16 on 2026-08-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_appointment_service_appointment_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Gerente/Administrador'), ('financial', 'Financeiro'), ('receptionist', 'Recepcionista'), ('professional', 'Profissional da Beleza'), ('support', 'Apoio (Faxina, Manutenção)')], default='professional', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('cpf', 'salon')},
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Comissão específica para este serviço. Se null, usa a comissão padrão do profissional.', max_digits=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='business.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='business.servicesalon')),
            ],
            options={
                'verbose_name': 'Serviço do Profissional',
                'verbose_name_plural': 'Serviços dos Profissionais',
                'db_table': 'employee_services',
                'unique_together': {('employee', 'service')},
            },
        ),
    ]
