# Generated by Django 5.2.16 on 2026-08-26 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_employee_role_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Opcional. Se vazio, é derivada da cor principal.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Informe uma cor em hexadecimal. Ex: #233B5C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Cor de Destaque'),
        ),
        migrations.AddField(
            model_name='salon',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nome curto exibido no menu e cabeçalho. Se vazio, usa o nome do salão.', max_length=60, verbose_name='Nome de Exibição'),
        ),
        migrations.AddField(
            model_name='salon',
            name='primary_color',
            field=models.CharField(default='#233B5C', help_text='Cor base da identidade visual em hexadecimal.', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor em hexadecimal. Ex: #233B5C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Cor Principal'),
        ),
        migrations.AddField(
            model_name='salon',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Opcional. Se vazio, é derivada da cor principal.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Informe uma cor em hexadecimal. Ex: #233B5C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='salon',
            name='tagline',
            field=models.CharField(blank=True, help_text='Frase curta exibida abaixo do nome. Ex: A beleza na palma da sua mão.', max_length=80, verbose_name='Slogan'),
        ),
    ]
