# Generated by Django 5.2.16 on 2026-08-27 20:00

import django.db.models.deletion
from django.db import migrations, models


def copy_professional_to_items(apps, schema_editor):
    Appointment = apps.get_model('business', 'Appointment')
    AppointmentItem = apps.get_model('business', 'AppointmentItem')
    
    # Iterate over appointments and set professional to items
    for appt in Appointment.objects.all():
        if appt.professional_id:
            AppointmentItem.objects.filter(appointment=appt).update(professional_id=appt.professional_id)

def reverse_copy_professional(apps, schema_editor):
    AppointmentItem = apps.get_model('business', 'AppointmentItem')
    # Can't accurately revert if multiple items had different professionals, 
    # but for simple rollback we take the first item's professional if it exists.
    for item in AppointmentItem.objects.all():
        if item.professional_id and not item.appointment.professional_id:
            item.appointment.professional_id = item.professional_id
            item.appointment.save(update_fields=['professional_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_salon_accent_color_salon_display_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='employeeservice',
            options={'verbose_name': 'Serviço do Colaborador', 'verbose_name_plural': 'Serviços dos Colaboradores'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Acréscimo'),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_items', to='business.employee', verbose_name='Profissional'),
        ),
        migrations.RunPython(copy_professional_to_items, reverse_copy_professional),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='prevent_double_booking',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='professional',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='business.customer'),
        ),
    ]
