# Generated by Django 5.2.16 on 2026-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_employee_options_alter_employeeservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
