"""
Django settings for salao_conecta project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost', cast=lambda v: [s.strip() for s in v.split(',')])

CORS_ORIGIN_ALLOW_ALL = config('CORS_ORIGIN_ALLOW_ALL', cast=bool, default=False)
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=lambda v: [s.strip() for s in v.split(',')],
                              default='http://localhost:3000, http://127.0.0.1:3000')

CORS_EXPOSE_HEADERS = [
    'Content-Disposition',
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-api-key',
    'x-requested-with',
    'X-Tenant-Slug'
]

SYSTEM_NAME = config('SYSTEM_NAME')

CODE_VERSION = 'v1.0.0'
ENVIRONMENT_SYSTEM = config('ENVIRONMENT_SYSTEM', default='PRODUCTION', cast=str.upper).strip('')

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

TRIGGER_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
]

LOCAL_APPS = [
    'core.apps.CoreConfig',
    'manager.apps.ManagerConfig',
    'auth_users.apps.AuthUserConfig',
    'business.apps.BusinessConfig',
    'financial.apps.FinancialConfig',
]

INSTALLED_APPS = DJANGO_APPS + TRIGGER_APPS + LOCAL_APPS

AUTH_USER_MODEL = 'auth_users.User'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'salao_conecta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salao_conecta.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DATABASE_ENGINE'),
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST', default='localhost'),
        'PORT': config('DATABASE_PORT', default='5432'),
        'TEST': {
            'NAME': config('DATABASE_TEST_NAME', default='test_salao_conecta'),
        },
    }
}

# Se existir um superusuário configurado para rodar os testes (criar/dropar test DB)
_db_superuser = config('DATABASE_SUPERUSER', default='')
if _db_superuser:
    DATABASES['default']['TEST']['USER'] = _db_superuser
    DATABASES['default']['TEST']['PASSWORD'] = config('DATABASE_SUPERUSER_PASSWORD', default='')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

APPEND_SLASH = False

ITENS_PER_PAGE = config('ITENS_PER_PAGE', cast=int, default=10)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': ITENS_PER_PAGE,
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '300/minute',
        'login_attempts': '5/minute'
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': SYSTEM_NAME,
    'DESCRIPTION': SYSTEM_NAME,
    'VERSION': CODE_VERSION,
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/schema',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
    },
    'REDOC_SETTINGS': {
        'theme': 'dark',
    },
    'CONTACT': {
        'name': 'JVM Sistemas',
        'url': 'https://jvmsistemas.com',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365) if ENVIRONMENT_SYSTEM == 'DEVELOPMENT' else timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=12),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

COOLDOWN_RESET_MINUTES = 5

# EMAIL
if ENVIRONMENT_SYSTEM == 'DEVELOPMENT':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",  # Mude para 'WARNING' se achar muito poluído
            "propagate": True,
        },
        # Para ver as SQL Queries
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Para logar erros da sua própria aplicação
        # Substitua 'app_name' pelo nome do seu app ou deixe vazio '' para pegar tudo
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

# # Garante que os cookies (se for usar) trafeguem apenas criptografados
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
#
# # Impede que o front-end (JavaScript) acesse o cookie CSRF
# CSRF_COOKIE_HTTPONLY = True
#
# # Força o navegador a sempre acessar seu backend via HTTPS por 1 ano
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
#
# # Impede que seu site seja "embutido" num iframe falso de outro site (Clickjacking)
# X_FRAME_OPTIONS = 'DENY'
#
# # Diz para o navegador não tentar adivinhar tipos de arquivos (MIME sniffing)
# SECURE_CONTENT_TYPE_NOSNIFF = True
